// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css'],
})
export class LivroListaComponent implements OnInit {
  editoras: Editora[] = [];
  livros: Livro[] = [];

  constructor(
    private controleEditoraService: ControleEditoraService,
    private controleLivrosService: ControleLivrosService
  ) {}

  ngOnInit(): void {
    this.carregarDados();
  }

  excluir(codigo: number): void {
    this.controleLivrosService.excluir(codigo);
    this.carregarLivros();
  }

  obterNomeEditora(codEditora: number): string {
    return this.controleEditoraService.getNomeEditora(codEditora);
  }

  private carregarDados(): void {
    this.carregarEditoras();
    this.carregarLivros();
  }

  private carregarEditoras(): void {
    this.editoras = this.controleEditoraService.getEditoras();
  }

  private carregarLivros(): void {
    this.livros = this.controleLivrosService.obterLivros();
  }
}

<main class="container">
  <h1>Catálogo de Livros</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Título</th>
        <th>Resumo</th>
        <th>Autores</th>
        <th>Editora</th>
        <th>Excluir</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.resumo }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>{{ obterNomeEditora(livro.codEditora) }}</td>
        <td>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">Excluir</button>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

const controleLivros = new ControleLivros();
const controleEditora = new ControleEditora();

const LivroLista = () => {
  const [livros, setLivros] = useState([]);
  const [carregando, setCarregando] = useState(true);

  useEffect(() => {
    const obterLivros = async () => {
      try {
        const livrosObtidos = await controleLivros.obterLivros();
        setLivros(livrosObtidos);
        setCarregando(false);
      } catch (error) {
        console.error(error);
        setCarregando(false);
      }
    };

    obterLivros();
  }, []);

  const excluirLivro = async codigo => {
    try {
      await controleLivros.excluirLivro(codigo);
      setLivros(livros => livros.filter(livro => livro.codigo !== codigo));
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <main>
      <h1>Catálogo de Livros</h1>
      {carregando ? (
        <p>Carregando livros...</p>
      ) : livros.length > 0 ? (
        <table className="table table-hover">
          <thead className="table-dark">
            <tr>
              <th>Título</th>
              <th>Resumo</th>
              <th>Editora</th>
              <th>Autores</th>
            </tr>
          </thead>
          <tbody>
            {livros.map((livro, index) => (
              <tr key={index}>
                <td>
                  <p>{livro.titulo}</p>
                  <button
                    className="btn btn-danger pull-right"
                    onClick={() => excluirLivro(livro.codigo)}
                  >
                    Excluir
                  </button>
                </td>
                <td>{livro.resumo}</td>
                <td>{controleEditora.getNomeEditora(livro.codEditora)}</td>
                <td>
                  <ul>
                    {livro.autores.map((autor, index) => (
                      <li key={index}>{autor}</li>
                    ))}
                  </ul>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      ) : (
        <p>Nenhum livro encontrado.</p>
      )}
    </main>
  );
};

export default LivroLista;
