// clientes/livros-react/src/LivroDados.js
import React, { useState, useEffect, useCallback, memo } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';
import { useNavigate } from 'react-router-dom';

const controleLivros = new ControleLivros();
const controleEditora = new ControleEditora();

const LivroDados = memo(() => {
  const [opcoes, setOpcoes] = useState([]);
  const [livro, setLivro] = useState({
    _id: null,
    codEditora: 0,
    titulo: '',
    resumo: '',
    autores: [],
  });
  const navigate = useNavigate();

  const fetchEditoras = useCallback(async () => {
    const editoras = await controleEditora.getEditoras();
    setOpcoes(editoras);
    setLivro(livro => ({
      ...livro,
      codEditora: editoras[0]?.codEditora || '',
    }));
  }, []);

  useEffect(() => {
    fetchEditoras();
  }, [fetchEditoras]);

  const tratarCombo = event => {
    setLivro({ ...livro, codEditora: event.target.value });
  };

  const incluir = event => {
    event.preventDefault();
    controleLivros.incluirLivro(livro).then(() => {
      navigate('/');
    });
  };

  return (
    <main>
      <h2>Dados do Livro</h2>
      <form onSubmit={incluir}>
        <div className="form-group">
          <label htmlFor="titulo">Título</label>
          <input
            id="titulo"
            className="form-control"
            type="text"
            value={livro.titulo}
            onChange={e => setLivro({ ...livro, titulo: e.target.value })}
            required
          />
        </div>
        <div>
          <label htmlFor="resumo">Resumo</label>
          <textarea
            id="resumo"
            className="form-control"
            value={livro.resumo}
            onChange={e => setLivro({ ...livro, resumo: e.target.value })}
            required
          />
        </div>
        <div>
          <label htmlFor="editora">Editora</label>
          <select
            id="editora"
            className="form-control"
            value={livro.codEditora}
            onChange={tratarCombo}
            required
          >
            {opcoes.map(item => (
              <option key={item.codEditora} value={item.codEditora}>
                {item.nome}
              </option>
            ))}
          </select>
        </div>
        <div>
          <label htmlFor="autores">Autores (1 por linha)</label>
          <textarea
            id="autores"
            className="form-control"
            value={livro.autores.join('\n')}
            onChange={e =>
              setLivro({ ...livro, autores: e.target.value.split('\n') })
            }
            required
          />
        </div>
        <button className="btn btn-primary" type="submit">
          Salvar Dados
        </button>
      </form>
    </main>
  );
});

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrls: ['./livro-dados.component.css'],
})
export class LivroDadosComponent implements OnInit {
  livro: Livro = new Livro(0, 0, '', '', []);
  autoresForm: string = '';
  editoras: Array<Editora> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split(/\r?\n/);
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  };
}

<main class="container">
  <h2>Registrar Livro</h2>
  <form (ngSubmit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título:</label>
      <input type="text" class="form-control" id="titulo" name="titulo" required [(ngModel)]="livro.titulo">
    </div>
    <div class="form-group">
      <label for="resumo">Resumo:</label>
      <textarea class="form-control" id="resumo" name="resumo" [(ngModel)]="livro.resumo"></textarea>
    </div>
    <div class="form-group">
      <label for="editora">Editora:</label>
      <select class="form-control" id="editora" name="editora" required [(ngModel)]="livro.codEditora">
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>
    <div class="form-group">
      <label for="autores">Autores:</label>
      <textarea class="form-control" id="autores" name="autores" [(ngModel)]="autoresForm"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>
</main>
